"                                   
"                    ██▒   █▓ ██▓ ███▄ ▄███▓ ██▀███   ▄████▄  
"                   ▓██░   █▒▓██▒▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█  
"                    ▓██  █▒░▒██▒▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄ 
"                     ▒██ █░░░██░▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒
"                      ▒▀█░  ░██░▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░
"                      ░ ▐░  ░▓  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░
"                      ░ ░░   ▒ ░░  ░      ░  ░▒ ░ ▒░  ░  ▒   
"                        ░░   ▒ ░░      ░     ░░   ░ ░        
"                         ░   ░         ░      ░     ░ ░      
"                        ░                           ░        

set nocompatible " be iMproved, required
set shell=bash\ --norc
set encoding=utf8

filetype off " required

syntax on

source ~/.dotfiles/config/vim/plugs.vim
source ~/.dotfiles/config/vim/binds.vim
source ~/.dotfiles/config/vim/tweak.vim

lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "c", "lua", "json", "javascript", "python", "rust", "typescript" },
    auto_install = true,
    highlight = {
        enable = true
    }
}
EOF

set background=dark
" set background=light
if (has("termguicolors"))
    set termguicolors
endif

" Colorschemes
" colorscheme catppuccin-latte
" colorscheme oxocarbon
colorscheme moonfly
" colorscheme everforest
" colorscheme gruvbox
" colorscheme dawnfox
