font_family      IosevkaTerm Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

scrollback_lines -1

shell /usr/local/bin/fish

editor vim

update_check_interval 0
